name: flutter_bizhan
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - images/1.png
  - images/2.png
  - images/3.png
  - images/4.png
  - images/home.png
  - images/home_selected.png
  - images/find.png
  - images/find_selected.png
  - images/mine.png
  - images/mine_selected.png
  - images/mines.png
  - images/mines_selected.png
  - images/sanscl.png
  - images/find.png
  - images/zhenshu.png
  - images/find_selected.png
  - images/gteq_icon_back.png
  - images/finla.jpg
  - images/ic_launcher.png
  - images/login_bg.jpg
  - images/mipmap-xhdpi-v4/gteq_login_icon_ser.png
  - images/mipmap-xhdpi-v4/gteq_login_icon_username.png
  - images/mipmap-xhdpi-v4/gteq_login_icon_pwd.png
  - images/mipmap-xhdpi-v4/gteq_login_down.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_go.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_myorder.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_uncheck.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_unbegin.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_myeqbug.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_doing.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_eqlist.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_pj.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_repair.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_appoint.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_repairlist.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_doing.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_addrepairrecord.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_inspect.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_upkeep.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_people.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_pwd.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_syn.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_tool.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_update.png
  - images/mipmap-xhdpi-v4/gteq_icon_main_our.png
  - images/mipmap-xhdpi-v4/gteq_icon_scan_addeqbug.png
  - images/mipmap-xhdpi-v4/gteq_head_portrait.png
  - images/music_icon_subject.png
  - images/longnv5.jpeg
  - images/longwuman3.jpg
  - images/lonnv6.jpg
  - images/lonvn9.jpg
  - images/lonnv8.jpg
  - images/lonnv10.jpg
  - images/mipmap-hdpi-v4/gteq_icon_order_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_order_pressed.png
  - images/mipmap-hdpi-v4/gteq_icon_eq_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_eq_pressed.png
  - images/mipmap-hdpi-v4/gteq_icon_pj_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_pj_pressed.png
  - images/mipmap-hdpi-v4/gteq_icon_plan_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_plan_pressed.png
  - images/mipmap-hdpi-v4/gteq_icon_mine_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_mine_pressed.png
  - images/mipmap-hdpi-v4/gteq_icon_statistics_normal.png
  - images/mipmap-hdpi-v4/gteq_icon_statistics_pressed.png
  - images/mipmap-hdpi-v4/next.png
  - images/mipmap-hdpi-v4/gteq_icon_scan.png
  - images/mipmap-hdpi-v4/gteq_icon_popu_down.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
